apiVersion: pytorch.monarch.io/v1
kind: MonarchMesh
metadata:
  name: monarch-demo-7
  namespace: monarch-workspace
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: monarch-worker
    spec:
      containers:
      - name: worker
        # The image label in the registry.
        image: ghcr.io/meta-pytorch/monarch:2025-12-16-alpha

        # Ensure we always try to pull (helpful during development)
        imagePullPolicy: Always

        # We use the default CMD from your Dockerfile ("python -u worker.py")
        # But we open the port for the mesh
        ports:
        - name: monarch
          containerPort: 26600

        # (Optional) Environment variables if your script needs them
        env:
        - name: MONARCH_PORT
          value: "26600"
        # TODO: Remove after thedavekwon merges his PR.
        # On containers where parent pid=1, the proc_mesh exits quickly without this envvar.
        - name: HYPERACTOR_MESH_BOOTSTRAP_ENABLE_PDEATHSIG
          value: "false"
